name: PR for feature to dev
on:
  push:
    branches:
      - feature/*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: create pull request
        run: gh pr create -B BE-DEV -H ${{ github.REF }} --title 'Merge ${{ github.REF }} into dev' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge ${{ steps.create-pull-request.outputs.pr-number }} --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      